version: 2
jobs:
  build:
    working_directory: ~/arachnid-build
    docker:
      - image: haskell:8.0
    steps:
      - checkout
      - restore_cache:
          key: stack-v2-{{ checksum "arachnid.cabal" }}
      - run:
          command: stack setup
      - run:
          command: stack test --coverage
      - run:
          name: Upload test coverage
          command: |
            apt-get update
            apt-get install curl bzip2 -y
            curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.4.0/shc-linux-x64-8.0.1.tar.bz2 | tar -xj
            ./shc --repo-token ${COVERALLS_REPO_TOKEN} arachnid spec doctest
      - save_cache:
          key: stack-v2-{{ checksum "arachnid.cabal" }}
          paths:
            - ~/.stack
