version: 2
jobs:
  build:
    working_directory: ~/arachnid-build
    docker:
      - image: haskell:8.0
    steps:
      - checkout
      - restore_cache:
          key: stack-cache-{{ checksum "arachnid.cabal" }}
      - run:
          command: stack setup
      - run:
          command: stack test --coverage
      - save_cache:
          key: stack-cache-{{ checksum "arachnid.cabal" }}
          paths:
            - ~/.stack
            - .stack-work
